{% set name = "earthaccess" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/{{ name }}/earthaccess-{{ version }}.tar.gz
  sha256: a71bdc6f722c4131c8525cde8b147011776260b274419ca38174debfa7f461a2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8,<4.0
    - poetry >=0.12
  run:
    - python >=3.8,<4.0
    - python-cmr >=0.7
    - python-benedict >=0.25
    - pqdm >=0.1
    - requests >=2.26
    - s3fs >=2021.11, <2024
    - fsspec >=2022.1
    - tinynetrc >=1.3.1
    - aiofiles >=0.8.0
    - aiohttp >=3.8.0
    - multimethod >=1.8
    - python-magic >=0.4

test:
  imports:
    - earthaccess
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/earthaccess/
  summary: Client Library for NASA Earthdata APIs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jhkennedy
    - betolink
