{% set name = "earthaccess" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/{{ name }}/earthaccess-{{ version }}.tar.gz
  sha256: 65eff69433687e3d1773a749e0a03c88034c9e197facb79cf1b4b0696c8895fc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8,<4.0
    - poetry >=0.12
  run:
    - python >=3.8,<4.0
    - python-cmr >=0.7
    - pqdm >=0.1
    - requests >=2.26
    - s3fs >=2021.11, <2024
    - fsspec >=2022.1
    - tinynetrc >=1.3.1
    - multimethod >=1.8

test:
  imports:
    - earthaccess
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/earthaccess/
  summary: Client Library for NASA Earthdata APIs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jhkennedy
    - betolink
