{% set name = "earthaccess" %}
{% set version = "0.10.0" %}
{% set sha256 = "318bddb33b08bb7087a76f46a628eef0fa12258aafad91008fecee02e6186f75" %}
{% set build_number = 0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/{{ name }}/earthaccess-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.9,<4.0
    - poetry-core >=1.0.0
  run:
    - python >=3.9,<4.0
    - python-cmr >=0.10.0
    - pqdm >=0.1
    - requests >=2.26
    - s3fs >=2022.11
    - fsspec >=2022.11
    - tinynetrc >=1.3.1
    - multimethod >=1.8
    - python-dateutil >=2.8.2
    - importlib-resources >=6.3.2
    - typing_extensions >=4.10.0

test:
  imports:
    - earthaccess
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/earthaccess/
  summary: Client Library for NASA Earthdata APIs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mfisher87
    - jrbourbeau
    - jhkennedy
    - betolink
