{% set name = "earthdata" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/earthdata-{{ version }}.tar.gz
  sha256: 23c8d2eabc508300a0e3a36749d52178685953a7e2fc2f209bd221823adcd0cf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --use-deprecated=out-of-tree-build

requirements:
  host:
    - pip
    - python >=3.8,<4.0
    - poetry >=0.12
  run:
    - python >=3.8,<4.0
    - python-cmr >=0.7
    - python-benedict >=0.25
    - pqdm >=0.1
    - requests >=2.26
    - s3fs >=2021.11, <2024
    - fsspec >=2022.1
    - tinynetrc >=1.3.1
    - aiofiles >=0.8.0
    - aiohttp >=3.8.0
    - multimethod >=1.8

test:
  imports:
    - earthdata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/earthdata/
  summary: Client library for NASA Earthdata APIs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jhkennedy
    - betolink
